initialize = require './initialize'
initialize()

require './services/movies'
require './services/navigation'
require './services/overlays'
require './services/menu'

require './directives/movie-list'
require './directives/movie-details'
require './directives/person-details'
require './directives/open-overlay'
require './directives/close-overlay'
require './directives/search'
require './directives/snap'
require './directives/overlay'
require './directives/swiper'
require './directives/menu'
require './directives/close-menu'
require './directives/open-menu'
require './directives/loading'
require './directives/back-button'
require './directives/offline'
require './directives/navigate'
require './directives/if-view'
require './directives/gain-focus'

require './filters/image-path'
require './filters/youtube-url'